### ISSUE TITLE
Does not open

### ISSUE THREAD

**Issue by Larmonster** [SuchByte/Macro-Deck#107]
*I double click Macro Deck to open it - nothing happens. I will wait a few minutes, still nothing so I right click and open and it says it's already running. So, I close it in task manager. Again try to open it, nothing happens. This is an endless cycle. 

Windows 11 - 64bit
Version: 21H2
OS build: 22000.376

**Comment by SuchByte** [comment]
Please send me your profiles.db located in "%Appdata%\Macro Deck". After you sent me it, you can rename it (just put a .old) after the filename and then it should work.

**Comment by Larmonster** [comment]
How do I do that?

**Comment by SuchByte** [comment]
I think it's way easier to help you if you join the Discord server: https://discord.gg/yr7TRaXum8

**Comment by Larmonster** [comment]
I have been trying but something is wrong with my phone number on discord. :-(

**Comment by Larmonster** [comment]
I am just trying to get the software to open...

**Comment by Larmonster** [comment]
I uninstalled and reinstalled and it did nothing to help

**Comment by dark-N00B** [comment]
Facing the same issue. Probably because of a plugin.
`19:27:08 [Macro Deck] [Info] >> Successfully read configuration file
19:27:08 [Macro Deck] [Info] >> Set language to English
19:27:08 [Macro Deck] [Info] >> VariableManager: Initialize variables database...
19:27:08 [Macro Deck] [Info] >> VariableManager: 45 variables found
19:27:08 [Macro Deck] [Info] >> PluginManager: Loading plugins...
19:27:08 [Macro Deck] [Info] >> Loading plugin HWiNFO64
19:27:08 [Macro Deck] [Info] >> Loading plugin AutoHotkey Plugin
19:27:08 [Macro Deck] [Info] >> Loading plugin KSoft.MediaInfo
19:27:08 [Macro Deck] [Info] >> Loading plugin Macro Deck Media Controls
19:27:08 [Macro Deck] [Info] >> Loading plugin Windows Utils
19:27:08 [Macro Deck] [Info] >> PluginManager: Enabling plugins...
19:27:08 [Macro Deck] [Error] >> MacroDeck: CurrentDomainOnUnhandledException: System.NullReferenceException: Object reference not set to an instance of an object.
   at Ize.HWiNFO64_Plugin.HWiNFO64Plugin.Enable() in C:\Users\Manuel\Desktop\Macro Deck Compiler\Temp\Ize.HWiNFO64\Main.cs:line 36
   at SuchByte.MacroDeck.Plugins.PluginManager.EnablePlugins() in E:\Repos\Macro-Deck-WinForms\Macro-Deck\Plugins\PluginManager.cs:line 492
   at SuchByte.MacroDeck.MacroDeck.Start(Boolean show, Int32 port) in E:\Repos\Macro-Deck-WinForms\Macro-Deck\MacroDeck.cs:line 447
   at SuchByte.MacroDeck.MacroDeck.Main(String[] args) in E:\Repos\Macro-Deck-WinForms\Macro-Deck\MacroDeck.cs:line 415`
   
   If I delete "Ize.HWiNFO64" folder from "%Appdata%\Macro Deck\plugins\" folder, Macro Deck runs once again
