### ISSUE TITLE
Stuck on "Quality" window when creating icon

### ISSUE THREAD

**Issue by S-Killen** [SuchByte/Macro-Deck#222]
When trying to create an icon (either import or create) I get to the select quality box and don't have an OK button to press

**To Reproduce**
1. Click on 'import icon'
2. Select image in explorer pop up
3. Select desired quality in Quality pop up window
4. Unable to proceed - no OK button visible

**Expected behavior**
I'd expect there to be some way to accept the selection

**Screenshots**
<img width="316" alt="image" src="https://user-images.githubusercontent.com/104443097/165320353-e1bba58c-1fd5-4ee1-9869-4c23e1c07c70.png">

**Additional context**

**Log file**
Please upload the latest log file (Help -> Export latest log)
[2022-04-26.log](https://github.com/SuchByte/Macro-Deck/files/8564043/2022-04-26.log)

**Comment by SuchByte** [comment]
This is a glitch because I think you're using a small, really high resolution display with a scale of >100%. You can temporarely fix this following these steps:
- Navigate to `C:\Program Files\Macro Deck` (Or the installation directory of Macro Deck) in the Windows Explorer
- Right click Macro Deck 2.exe and click "Properties"
- Click "Compatibility" and then "Change high DPI settings"
- Now check "Override high DPI scaling behaviour" and select "System (Enchanced)"
- Then you can close the dialoges with "Ok"
